name: shared_preferences_moretypes
description: extension of shared prefernces so more variables can be stored easily
version: 3.0.0
repository: https://github.com/Robert3141/shared_preferences_moretypes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # external packages
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


